---
include:
  - board: seeeduino_xiao_ble
    shield: Solstice_L rgbled_adapter dongle_display
    # shield: Solstice_L rgbled_adapter nice_oled
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: Solstice_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: settings_reset